# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ main ]
  workflow_dispatch:


jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2      
      - name: deploy
        run: |
          npm install
          npm run deploy
